### PR TITLE
Crud

### PR DESCRIPTION
**Pull request by alex-videll**
Not sure if the tests are right, could definitely use another set of eyes

### CODE REVIEW

**Comment by webqatutor** [comment]
because we integrated`Devise` with application based on the ticket with the title `Integrate with front-end framework and devise` we don't need to create `UsersController` because it handled by Devise. You can see `devise_for :users` in `routes.rb` what is similar to CRUD but handled by gem itself. I think we have a bug in requirements of the ticket with the title `Build CRUD for a Games Controller`

**Comment by webqatutor** [comment]
I reviewed the tests. I think the factory for the game is missing and the factory for the user is blank. We need to add some code. For example:
```
factory :user do
    sequence(:email) { |n| "dummyEmail#{n}@1.com" }
    password { "secretPassword" }
    password_confirmation { "secretPassword" }
  end
```

**Comment by alex-videll** [comment]
What file would this go in? Would it be its own?

**Comment by webqatutor** [comment]
The factory for the user is here ` chess/spec/factories/users.rb `. We need to add code there. 
I attach the link on the lesson with examples. https://online.bootcampspot.com/tdd/11

**Comment by webqatutor** [comment]
We also need a factory for a game too. But to make it work we need to create a model Game before. Otherwise, tests won't work.

**Comment by alex-videll** [comment]
Ok, I'll get back to it in a bit. Thanks for the help!

**Comment by webqatutor** [comment]
I'm glad to help.

**Pull request merged**
